server:
  port: 8080

aws:
  cognito:
    region: ${AWS_COGNITO_REGION:ap-northeast-2}
    jwk-set-uri: ${AWS_COGNITO_JWK_SET_URI:https://dummy}

spring:
  application:
    name: service-cart


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${COGNITO_JWK_SET_URI}
  data:
    redis:
      host: ${REDIS_HOST:master.courm-redis-prod.epf9hv.apn2.cache.amazonaws.com}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:

      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:cart-service-group}
      enable-auto-commit: false
      auto-offset-reset: earliest

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.groom.common.event.envelope.EventEnvelope
        spring.json.use.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      probes:
        enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

logging:
  level:
    com.groom: ${LOG_LEVEL:INFO}

external:
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://product-service-dev-courm-app-active}

event:
  kafka:
    topics:
      order: ${KAFKA_ORDER_TOPIC:order-events}
      payment: ${KAFKA_PAYMENT_TOPIC:payment-events}
      product: ${KAFKA_PRODUCT_TOPIC:product-events}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

