server:
  port: 8080

spring:
  application:
    name: service-user
  datasource:
    url: jdbc:postgresql://postgres.dev.svc.cluster.local:5432/user_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      #host: localhost
      host: local-redis
      port: 6379

  kafka:
    bootstrap-servers: 10.0.20.101:9091,10.0.20.35:9091,10.0.21.159:9091
    #bootstrap-servers: 10.0.20.113:9092,10.0.20.89:9092,10.0.21.141:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: service-user
      enable-auto-commit: false
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.groom.common.event.envelope.EventEnvelope
        spring.json.use.type.headers: false

jwt:
  secret: your-secret-key-should-be-at-least-256-bits-long-for-hs256
  expiration: 3600000

logging:
  level:
    com.groom: DEBUG
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

event:
  kafka:
    topics:
      user: user-lifecycle
  envelope:
    version: "1.0"

# cognito
aws:
  cognito:
    region: ap-northeast-2
    user-pool-id: ap-northeast-2_HmqfrWP3T
    client-id: 7dhk1lsqh5c1v9gqh1evtdlpoq
    jwk-set-uri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_HmqfrWP3T/.well-known/jwks.json
    client-secret: 8iqncgv83mbnmion6f06rlj4mvib1ii0adg7po283g0vss9581p

# prometheus
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus   # /actuator/health, /actuator/info, /actuator/prometheus 노출

  endpoint:
    prometheus:
      enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true                # p95/p99 계산용 bucket 생성
      percentiles:
        http:
          server:
            requests: 0.5,0.95,0.99       # 퍼센타일도 직접 노출
